ProjectPertamina.Presentation/Controllers/Tabel56Controller.cs
using DataTables.Mvc;
using OfficeOpenXml;
using ProjectPertamina.Entities.Models.WebCustodyTransfer;
using ProjectPertamina.Presentation.Common;
using ProjectPertamina.Services.WebCustodyTransfer;
using ProjectPertamina.UserManager;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectPertamina.Presentation.Controllers
{
    [PertaminaAuthorize]
    public class Tabel56Controller : Controller
    {
        private ITabel56Service _tabel56Service;
        private CurrentUser user = CurrentUser.GetCurrentUser();
        public Tabel56Controller(ITabel56Service Tabel56Service)
        {
            _tabel56Service = Tabel56Service;
        }
        // GET: MasterTabel56
        public ActionResult Index()
        {
            ViewBag.Create = user.ActionCreate;
            ViewBag.Edit = user.ActionUpdate;
            ViewBag.Delete = user.ActionDelete;

            return View();
        }

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel, decimal Density, decimal Liter)
        {
            var obj = _tabel56Service.SearchTabel56(requestModel.Start, requestModel.Length, Density, Liter);

            var data = obj.Item1.Select(camp => new
            {
                Id = camp.Id,
                Density = camp.Density15,
                Liter = camp.LiterMetricTon,
            });
            return Json(new DataTablesResponse(requestModel.Draw, data.ToList(), obj.Item3, obj.Item2), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Upload()
        {
            return PartialView("_Upload");
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase FileUpload)
        {
            int rowIterator = 0;
            List<Tabel56> Tabel56List = new List<Tabel56>();

            try
            {
                if (FileUpload != null)
                {
                    if ((FileUpload != null) && (FileUpload.ContentLength > 0) && !string.IsNullOrEmpty(FileUpload.FileName))
                    {
                        string fileName = FileUpload.FileName;
                        string fileContentType = FileUpload.ContentType;
                        byte[] fileBytes = new byte[FileUpload.ContentLength];
                        var data = FileUpload.InputStream.Read(fileBytes, 0, Convert.ToInt32(FileUpload.ContentLength));

                        List<Tabel56> ListTabel56 = _tabel56Service.GetAll().ToList();
                        using (var package = new ExcelPackage(FileUpload.InputStream))
                        {
                            var currentSheet = package.Workbook.Worksheets;
                            var workSheet = currentSheet.First();
                            var noOfCol = workSheet.Dimension.End.Column;
                            var noOfRow = workSheet.Dimension.End.Row;
                            if (workSheet.Cells[1, 1].Value.ToString() != "Density 15" ||
                                workSheet.Cells[1, 2].Value.ToString() != "Liter/Metric Ton" ||
                                noOfCol > 2)
                            {
                                ViewBag.Error = $"Maaf template yang anda upload salah.<br>Mohon downlod kembali template Table 56.";
                                return View("_Upload");
                            }
                            if (noOfRow == 1)
                            {
                                ViewBag.Error = $"Harap masukan data terlebih dahulu.";
                                return View("_Upload");
                            }
                            for (rowIterator = 2; rowIterator <= noOfRow; rowIterator++)
                            {
                                var obj = new Tabel56();
                                obj.Density15 = decimal.Parse(workSheet.Cells[rowIterator, 1].Value.ToString());
                                if (ListTabel56.Where(i => i.Density15 == obj.Density15).FirstOrDefault() != null || Tabel56List.Where(i => i.Density15 == obj.Density15).FirstOrDefault() != null)
                                {
                                    ViewBag.Error = $"Data sudah diupload sampai baris ke {rowIterator - 1} <br>Density15 baris ke {rowIterator} gagal, karena data sudah ada.";
                                    if (rowIterator == 2)
                                        ViewBag.Error = $"Density15 baris ke {rowIterator} gagal, karena data sudah ada.<br>Tidak ada data yang terupload.";

                                    _tabel56Service.AddRange(Tabel56List);

                                    return View("_Upload");
                                }

                                obj.LiterMetricTon = decimal.Parse(workSheet.Cells[rowIterator, 2].Value.ToString());

                                Tabel56List.Add(obj);
                            }

                            _tabel56Service.AddRange(Tabel56List);
                        }
                    }
                }
                return Content("success");
            }
            //catch (DbUpdateException ex)
            //{
            //    ViewBag.Error = $"Code baris ke {rowIterator} sudah ada.";
            //    return View("_Upload");
            //}
            catch (NullReferenceException)
            {
                ViewBag.Error = $"Data sudah diupload sampai baris ke {rowIterator - 1} <br>Terdapat data kosong pada baris ke {rowIterator}";
                _tabel56Service.AddRange(Tabel56List);
                //ModelState.AddModelError("", $"Terdapat data kosong pada baris ke {rowIterator}");
                return View("_Upload");
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"Input Gagal, tidak ada data yang diinput.";
                ModelState.AddModelError("", ex.Message);
                return View("_Upload");
            }

        }

        public ActionResult Create(int id = 0)
        {
            var tabel56 = _tabel56Service.Get(id);
            ViewBag.Title = "EDIT";
            if (tabel56 == null)
            {
                tabel56 = new Tabel56();
                ViewBag.Title = "ADD";
            }

            return PartialView("_CreateEdit", tabel56);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateEdit(Tabel56 model)
        {
            ViewBag.Title = model.Id == 0 ? "ADD" : "EDIT";
            if (!ModelState.IsValid)
            {
                return View("_CreateEdit", model);
            }
            try
            {
                _tabel56Service.Save(model);
                return Content("success");
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("Density15", "Data sudah ada");
                return View("_CreateEdit", model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("_CreateEdit", model);
            }
        }

        public ActionResult Delete(int Id)
        {
            var tabel56 = _tabel56Service.Get(Id);
            return PartialView("_Delete", tabel56);
        }

        // POST: Admin/Role/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteAction(int id)
        {
            try
            {
                _tabel56Service.Delete(id);
                return Content("success");
            }
            catch (DbUpdateException ex)
            {
                var sqlException = ex.GetBaseException() as SqlException;
                var tabel56 = _tabel56Service.Get(id);

                if (sqlException != null)
                {
                    var number = sqlException.Number;

                    if (number == 547)
                    {
                        ModelState.AddModelError("", "Data tidak dapat dihapus karena sudah digunakan.");
                        return View("_Delete", tabel56);
                    }
                }
                ModelState.AddModelError("", ex.Message);
                return View("_Delete", tabel56);
            }
            catch (Exception ex)
            {
                var tabel56 = _tabel56Service.Get(id);
                ModelState.AddModelError("", ex.Message);
                return View("_Delete", tabel56);
            }
        }

        public JsonResult GetLiter15FromTabel56(decimal mt, decimal density)
        {
            decimal d1 = Math.Truncate(density * 1000) / 1000;
            decimal d2 = d1 + (decimal)0.001;
            decimal d3 = d1 + (decimal)0.001;
            decimal d4 = d2 + (decimal)0.001;
            Tabel56 d5Obj = _tabel56Service.Find(i => i.Density15 == d1).FirstOrDefault();
            Tabel56 d6Obj = _tabel56Service.Find(i => i.Density15 == d2).FirstOrDefault();
            if (d5Obj == null)
                return Json(new { Liter15 = "Master Tabel56 tidak ditemukan", val = false }, JsonRequestBehavior.AllowGet);

            if (d6Obj == null)
                return Json(new { Liter15 = "Master Tabel56 tidak ditemukan", val = false }, JsonRequestBehavior.AllowGet);

            decimal d5 = d5Obj.LiterMetricTon;
            decimal d6 = d6Obj.LiterMetricTon;

            decimal Liter15 = mt * (d5 + ((density - d1) / (decimal)0.001 * (d6 - d5)));
            //Liter15 = Math.Round(Liter15, 0);
            return Json(new { Liter15 = Liter15, val = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjectPertamina.Presentation/Views/Tabel56/Index.cshtml
@model ProjectPertamina.Entities.Models.WebCustodyTransfer.Tabel56
<div class="container-content">
    <div class="title-admin">
        TABEL 56
    </div>
    <div class="isi-content">
        <div class="row sorting-table">
            <div class="col-md-10">
                <form class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(i => i.Density15, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-3">
                            @Html.TextBox("Density15", "", new { @class = "form-control", type = "number", step = "0,001" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(i => i.LiterMetricTon, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-3">
                            @Html.TextBox("LiterMetricTon", "", new { @class = "form-control", type = "number", step="0,1" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-9">
                            <input type="button" class="btn btn-primary btn-sm" value="Search" id="btnSearch" />
                        </div>
                    </div>
                </form>
            </div>
        </div>

        @if (ViewBag.Create == true)
            {
            <div class="table-header">
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-url="@Url.Action("Create", "Tabel56")" id="btnCreate">Add Tabel 56</button>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-url="@Url.Action("Upload", "Tabel56")" id="btnUploadExcel">Upload Excel</button>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" id="ButtonDownload">Download Template</button>
            </div>
        }
        <input type="hidden" id="hdActionedit" value="@ViewBag.Edit.ToString()" />
        <input type="hidden" id="hdActiondelete" value="@ViewBag.Delete.ToString()" />
        <table id="Table" class="table table-striped table-bordered" cellspacing="0" style="width:100%"></table>
    </div>
</div>

<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="CreateAssetModal" aria-hidden="true" data-backdrop="static">
    <div id="createContainer">
    </div>
</div>

<script type="text/javascript">
    //Other Script
    $("#ButtonDownload").on("click", function (e) {
        e.preventDefault();  //stop the browser from following
        window.location.href = 'ExcelTemplate/Tabel56_Template.xlsx';
    });
</script>

<script type="text/javascript">
    //Table Script
    var assetListVM;
    //Login
    var edit = $('#hdActionedit').val();
    var hapus = $('#hdActiondelete').val();
    var visible = true;
    if (edit == "False" && hapus == "False")
        visible = false;
    //Login
    $(function () {
        assetListVM = {
            dt: null,

            init: function () {
                dt = $('#Table').DataTable({
                    "serverSide": true,
                    "processing": true,
                    "searching": false,
                    "ordering": false,
                    "ajax": {
                        "url": "@Url.Action("Get","Tabel56")",
                        "data": function (data) {
                            //function search
                            data.Density = parseFloat($("#Density15").val() == "" ? 0 : $("#Density15").val());
                            data.Liter = parseFloat($("#LiterMetricTon").val() == "" ? 0 : $("#LiterMetricTon").val());
                        }
                    },
                    "columns": [
                        {
                            "className": "dt-center",
                            "width": "100px",
                            "title": "<span class='glyphicon glyphicon-cog'></span>",
                            "data": "Id",
                            "sortable": false,
                            "render": function (data, type, full, meta) {
                                var action = "";
                                if (edit == "True") {
                                    action = '<a class="btn btn-primary btn-sm editAsset" href="@Url.Action("Create", "Tabel56")?Id=' + data + '"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>';
                                }
                                if (hapus == "True") {
                                    action = action + ' <a href="@Url.Action("Delete", "Tabel56")?Id=' + data + '" class="delete btn btn-danger btn-sm delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>';
                                }
                                return action;
                            }
                        },
                        { "title": "Density", "data": "Density", "sortable": false },
                        { "title": "Liter/Metric Ton", "data": "Liter", "sortable": false },
                    ],
                    "columnDefs": [
                        {
                            "targets": [0],
                            "visible": visible
                        },
                        {
                            "targets": [1],
                            "render": function (data, type, row) {
                                return '' + accounting.formatNumber(data, 3, ",", ".") + '';
                            },
                        },
                        {
                            "targets": [2],
                            "render": function (data, type, row) {
                                return '' + accounting.formatNumber(data, 1, ",", ".") + '';
                            },
                        }
                    ],
                    "lengthMenu": [[10, 25, 50, 100], [10, 25, 50, 100]],
                    "dom": '<"top">rt<"bottom"lip><"clear">'
                });
            },

            refresh: function () {
                dt.ajax.reload();
            }
        }
        $('#btnSearch').on("click", assetListVM.refresh);

        assetListVM.init();

        $("#btnCreate").on("click", function () {

            var url = $(this).data("url");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $('#Table').on("click", ".editAsset", function (event) {

            event.preventDefault();

            var url = $(this).attr("href");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $("#btnUploadExcel").on("click", function () {

            var url = $(this).data("url");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $('#Table').on("click", ".delete", function (event) {

            event.preventDefault();

            var url = $(this).attr("href");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });
    });

</script>

ProjectPertamina.Presentation/Views/Tabel56/_CreateEdit.cshtml
@model ProjectPertamina.Entities.Models.WebCustodyTransfer.Tabel56

@{
    Layout = null;
}

<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">@ViewBag.Title TABEL 56</h4>
        </div>
        @using (Ajax.BeginForm("CreateEdit", "Tabel56", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "CreateSuccess" }, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group required">
                        @Html.LabelFor(model => model.Density15, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-sm-8">
                            @if (ViewBag.Title == "ADD")
                            {
                                @Html.TextBoxFor(model => model.Density15, new { @class = "form-control", type = "number", step = "0.001" })
                            }
                            else
                            {
                                @Html.TextBoxFor(model => model.Density15, new { @class = "form-control", type = "number", @readonly = "", step = "0.001" })
                            }
                            @Html.ValidationMessageFor(model => model.Density15, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group required">
                        @Html.LabelFor(model => model.LiterMetricTon, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(i => i.LiterMetricTon, new { @class = "form-control", type = "number", step = "0.1" })
                            @Html.ValidationMessageFor(model => model.LiterMetricTon, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary btn-sm" value="Save" />
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
            </div>
        }
    </div>
</div>

ProjectPertamina.Presentation/Views/Tabel56/_Delete.cshtml
@model ProjectPertamina.Entities.Models.WebCustodyTransfer.Tabel56

@{
    Layout = null;
    ViewBag.Title = "Delete";
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Delete</h4>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h4>Apakah Anda yakin menghapus (Density 15 =  @string.Format("{0:n3}", Model.Density15))?</h4>

        </div>

        <div class="modal-body">
            @using (Ajax.BeginForm("Delete", "Tabel56", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "DeleteSuccess" }, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="form-actions no-color">
                    @Html.HiddenFor(x => x.Id)
                    <input type="submit" value="Delete" class="btn btn-default btn-sm" />
                    <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Cancel</button>
                </div>
            }
        </div>
    </div>
</div>

ProjectPertamina.Presentation/Views/Tabel56/_Upload.cshtml
@using ProjectPertamina.Common

@{
    Layout = null;
}

<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">UPLOAD TABEL 56</h4>
        </div>
        <form id="FormPopup">
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @*<div class="form-group">
                            @Html.Label("DownloadFile", "Template Excel", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-3">
                                <input type="button" class="btn btn-primary btn-sm" value="Download" id="ButtonDownload"/>
                            </div>
                        </div>*@
                    <div class="form-group divgambar" data-provides="fileupload">
                        @Html.Label("NamaFile", "Excel", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            <input type="file" class="form-control" name="InputExcel" id="InputExcel" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
                            <p class="text-danger" id="ErrorMsg">@Html.Raw(ViewBag.Error)</p>
                            @Html.ValidationMessage("tes", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-primary btn-sm" value="Save" id="ButtonSave" data-url="@Url.Action("Upload","Tabel56")" />
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $("#ButtonSave").on("click", function () {
        LoadingBar();

        var url = $(this).data("url");

        var data = new FormData();
        var files1 = $("#InputExcel").get(0).files;
        if (files1.length > 0) {
            data.append("FileUpload", files1[0]);
        }
        else {
            $("#ErrorMsg").html("Harap masukan file Excel");
            return;
        }

        $.ajax({
            url: url + '?' + $("#FormPopup").serialize(),
            type: "POST",
            data: data,
            contentType: false,
            processData: false,
            success: function (data) {
                swal.close();
                CreateSuccess2(data);
            },
            error: function (err) {
                swal(err.statusText);
            }
        });

    });

</script>