ProjectPertamina.Presentation/Controllers/PortController.cs
using DataTables.Mvc;
using ProjectPertamina.Entities.Models;
using ProjectPertamina.Presentation.Common;
using ProjectPertamina.Services;
using ProjectPertamina.UserManager;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace ProjectPertamina.Presentation.Controllers
{
    [PertaminaAuthorize]
    public class PortController : Controller
    {
        private IPortService _portService;
        private CurrentUser user = CurrentUser.GetCurrentUser();
        public PortController(IPortService PortService)
        {
            _portService = PortService;
        }
        // GET: Port
        public ActionResult Index()
        {
            ViewBag.Create = user.ActionCreate;
            ViewBag.Edit = user.ActionUpdate;
            ViewBag.Delete = user.ActionDelete;
            return View();
        }

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel, string Code, string Desc)
        {
            var obj = _portService.SearchPort(requestModel.Start, requestModel.Length, Code, Desc);

            var data = obj.Item1.Select(camp => new
            {
                Id = camp.Id,
                RoasAsalTujuan = camp.RoasAsalTujuan,
                Code = camp.Code,
                Desc = camp.Description
            });

            return Json(new DataTablesResponse(requestModel.Draw, data.ToList(), obj.Item3, obj.Item2), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(int id = 0)
        {
            var port = _portService.Get(id);
            ViewBag.Title = "EDIT";
            if (port == null)
            {
                port = new Port();
                ViewBag.Title = "ADD";
            }

            return PartialView("_CreateEdit", port);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateEdit(Port model)
        {
            ViewBag.Title = model.Id == 0 ? "ADD" : "EDIT";
            if (!ModelState.IsValid)
            {
                return View("_CreateEdit", model);
            }
            try
            {
                model.Code = Regex.Replace(model.Code, @"\t|\n|\r", "");
                model.Code = model.Code.Trim();
                _portService.Save(model);
                return Content("success");
            }
            catch (DbUpdateException ex)
            {

                ModelState.AddModelError("RoasAsalTujuan", "Data sudah ada");
                return View("_CreateEdit", model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("_CreateEdit", model);
            }
        }



        public ActionResult Delete(int Id)
        {
            var port = _portService.Get(Id);
            return PartialView("_Delete", port);
        }

        // POST: Admin/Role/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteAction(int id)
        {
            try
            {
                _portService.Delete(id);
                return Content("success");
            }
            catch (DbUpdateException ex)
            {
                var sqlException = ex.GetBaseException() as SqlException;
                var cargo = _portService.Get(id);

                if (sqlException != null)
                {
                    var number = sqlException.Number;

                    if (number == 547)
                    {
                        ModelState.AddModelError("", "Data tidak dapat dihapus karena sudah digunakan.");
                        return View("_Delete", cargo);
                    }
                }
                ModelState.AddModelError("", ex.Message);
                return View("_Delete", cargo);
            }
            catch (Exception ex)
            {
                var cargo = _portService.Get(id);
                ModelState.AddModelError("", ex.Message);
                return View("_Delete", cargo);
            }
        }
    }
}

ProjectPertamina.Presentation/Views/Port/Index.cshtml
@model ProjectPertamina.Entities.Models.Port

<div class="container-content">
    <div class="title-admin">
        PORT
    </div>
    <div class="isi-content">
        <div class="row sorting-table">
            <div class="col-md-10">
                <form class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(i => i.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-3">
                            @Html.TextBox("Code", "", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(i => i.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-3">
                            @Html.TextBox("Description", "", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-9">
                            <input type="button" class="btn btn-primary btn-sm" value="Search" id="btnSearch" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @if (ViewBag.Create == true)
        {
            <div class="table-header">
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-url="@Url.Action("Create", "Port")" id="btnCreate">Add Port</button>
            </div>
        }
        <input type="hidden" id="hdActionedit" value="@ViewBag.Edit.ToString()" />
        <input type="hidden" id="hdActiondelete" value="@ViewBag.Delete.ToString()" />
        <table id="Table" class="table table-striped table-bordered" cellspacing="0" width="100%"></table>
    </div>
</div>

<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="CreateAssetModal" aria-hidden="true" data-backdrop="static">
    <div id="createContainer">
    </div>
</div>

@*<script type="text/javascript">
        //Other Script
        $("#ButtonDownload").on("click", function (e) {
            e.preventDefault();  //stop the browser from following
            window.location.href = 'ExcelTemplate/Port_Template.xlsx';
        });
    </script>*@

<script type="text/javascript">
    //Table Script
    var assetListVM;
    var edit = $('#hdActionedit').val();
    var hapus = $('#hdActiondelete').val();
    var visible = true;
    if (edit == "False" && hapus == "False")
        visible = false;
    $(function () {
        assetListVM = {
            dt: null,

            init: function () {
                dt = $('#Table').DataTable({
                    "serverSide": true,
                    "processing": true,
                    "searching": false,
                    "ordering": false,
                    "ajax": {
                        "url": "@Url.Action("Get","Port")",
                        "data": function (data) {
                            //function search
                            data.Code = $("#Code").val();
                            data.Desc = $("#Description").val();
                        }
                    },
                    "columnDefs": [
                        {
                            "targets": [0],
                            "visible": visible
                        },
                    ],
                    "columns": [
                        {
                            "className": "dt-center",
                            "width": "100px",
                            "title": "<span class='glyphicon glyphicon-cog'></span>",
                            "data": "Id",
                            "sortable": false,
                            "render": function (data, type, full, meta) {
                                var action = "";
                                if (edit == "True") {
                                    action = '<a class="btn btn-primary btn-sm editAsset" href="@Url.Action("Create", "Port")?Id=' + data + '"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>';
                                }
                                if (hapus == "True") {
                                    action = action + ' <a href="@Url.Action("Delete", "Port")?Id=' + data + '" class="delete btn btn-danger btn-sm delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>';
                                }
                                return action;
                            }
                        },
                        { "title": "Roas Asal Tujuan", "data": "RoasAsalTujuan", "sortable": false },
                        { "title": "Kode", "data": "Code", "sortable": false },
                        { "title": "Deskripsi", "data": "Desc", "sortable": false },
                    ],
                    "lengthMenu": [[10, 25, 50, 100], [10, 25, 50, 100]],
                    "dom": '<"top">rt<"bottom"lip><"clear">'
                });
            },

            refresh: function () {
                dt.ajax.reload();
            }
        }
        $('#btnSearch').on("click", assetListVM.refresh);

        assetListVM.init();

        $("#btnCreate").on("click", function () {

            var url = $(this).data("url");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $('#Table').on("click", ".editAsset", function (event) {

            event.preventDefault();

            var url = $(this).attr("href");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $('#Table').on("click", ".delete", function (event) {

            event.preventDefault();

            var url = $(this).attr("href");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

    });

</script>

ProjectPertamina.Presentation/Views/Port/_CreateEdit.cshtml
@model ProjectPertamina.Entities.Models.Port

@{
    Layout = null;
}

<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">@ViewBag.Title PORT</h4>
        </div>
        @using (Ajax.BeginForm("CreateEdit", "Port", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "CreateSuccess" }, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group required">
                        @Html.LabelFor(model => model.RoasAsalTujuan, new { @class = "control-label col-md-3" })
                        <div class="col-sm-8">
                            @if (ViewBag.Title == "ADD")
                            {
                                @Html.EditorFor(model => model.RoasAsalTujuan, new { htmlAttributes = new { @class = "form-control", maxlength = "50" } })
                            }
                            else
                            {
                                @Html.EditorFor(model => model.RoasAsalTujuan, new { htmlAttributes = new { @class = "form-control", maxlength = "50", @readonly = "" } })
                            }
                            @Html.ValidationMessageFor(model => model.RoasAsalTujuan, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group required">
                        @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-3" })
                        <div class="col-sm-8">
                            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", maxlength = "12" } })
                            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group required">
                        @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-3" })
                        <div class="col-sm-8">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", maxlength = "250" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary btn-sm" value="Save" />
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                </div>
        }
    </div>
</div>

ProjectPertamina.Presentation/Views/Port/_Delete.cshtml
@model ProjectPertamina.Entities.Models.Port

@{
    Layout = null;
    ViewBag.Title = "Delete";
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Delete</h4>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h4>Apakah Anda yakin menghapus (@Html.DisplayFor(model => model.Description))?</h4>

        </div>

        <div class="modal-body">
            @using (Ajax.BeginForm("Delete", "Port", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "DeleteSuccess" }, new { @class = "form-horizontal", role = "form" }))
            {

                <div class="form-actions no-color">
                    @Html.HiddenFor(x => x.Id)
                    <input type="submit" value="Delete" class="btn btn-default btn-sm" />
                    <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Cancel</button>
                </div>
            }
        </div>
    </div>
</div>