ProjectPertamina.Presentation/Controllers/CargoController.cs
using DataTables.Mvc;
using OfficeOpenXml;
using ProjectPertamina.Entities.Models;
using ProjectPertamina.Presentation.Common;
using ProjectPertamina.Services;
using ProjectPertamina.UserManager;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectPertamina.Presentation.Controllers
{
    [PertaminaAuthorize]
    public class CargoController : Controller
    {
        private ICargoService _cargoService;
        private CurrentUser user = CurrentUser.GetCurrentUser();
        public CargoController(ICargoService CargoService)
        {
            _cargoService = CargoService;
        }
        // GET: MasterCargo
        public ActionResult Index()
        {
            ViewBag.Create = user.ActionCreate;
            ViewBag.Edit = user.ActionUpdate;
            ViewBag.Delete = user.ActionDelete;

            return View();
        }

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel, string Code, string Desc)
        {
            var obj = _cargoService.SearchCargo(requestModel.Start, requestModel.Length, Code, Desc);

            var data = obj.Item1.Select(camp => new
            {
                Id = camp.Id,
                Code = camp.Code,
                Desc = camp.Description
            });

            return Json(new DataTablesResponse(requestModel.Draw, data.ToList(), obj.Item3, obj.Item2), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Upload()
        {
            return PartialView("_Upload");
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase FileUpload)
        {
            int rowIterator = 0;
            try
            {
                if (FileUpload != null)
                {
                    if ((FileUpload != null) && (FileUpload.ContentLength > 0) && !string.IsNullOrEmpty(FileUpload.FileName))
                    {
                        string fileName = FileUpload.FileName;
                        string fileContentType = FileUpload.ContentType;
                        byte[] fileBytes = new byte[FileUpload.ContentLength];
                        var data = FileUpload.InputStream.Read(fileBytes, 0, Convert.ToInt32(FileUpload.ContentLength));

                        using (var package = new ExcelPackage(FileUpload.InputStream))
                        {
                            var currentSheet = package.Workbook.Worksheets;
                            var workSheet = currentSheet.First();
                            var noOfCol = workSheet.Dimension.End.Column;
                            var noOfRow = workSheet.Dimension.End.Row;
                            if (noOfRow == 1)
                            {
                                ViewBag.Error = $"Harap masukan data terlebih dahulu.";
                                return View("_Upload");
                            }
                            for (rowIterator = 2; rowIterator <= noOfRow; rowIterator++)
                            {
                                var obj = new Cargo();
                                obj.Code = workSheet.Cells[rowIterator, 1].Value.ToString().Trim();
                                //var asd = _cargoService.Find(i => i.Code == obj.Code).FirstOrDefault();
                                //if (_cargoService.Find(i => i.Code == obj.Code).FirstOrDefault() != null)
                                //{
                                //    ViewBag.Error = $"Code baris ke {rowIterator} sudah ada.";
                                //    return View("_Upload");
                                //}
                                obj.Description = workSheet.Cells[rowIterator, 2].Value.ToString();

                                _cargoService.Save(obj);
                            }
                        }
                    }
                }
                return Content("success");
            }
            catch (DbEntityValidationException ex)
            {

                ViewBag.Error = $"baris ke {rowIterator} :";
                foreach (var entityValidationErrors in ex.EntityValidationErrors)
                {
                    foreach (var validationError in entityValidationErrors.ValidationErrors)
                    {
                        ViewBag.Error += $"<br>{validationError.ErrorMessage}";
                        //Response.Write("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                    }
                }
                return View("_Upload");
            }
            catch (DbUpdateException)
            {
                ViewBag.Error = $"Code baris ke {rowIterator} sudah ada.";
                return View("_Upload");
            }
            catch (NullReferenceException)
            {
                ViewBag.Error = $"Terdapat data kosong pada baris ke {rowIterator}";
                //ModelState.AddModelError("", $"Terdapat data kosong pada baris ke {rowIterator}");
                return View("_Upload");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("_Upload");
            }

        }

        public ActionResult Create(int id = 0)
        {
            var cargo = _cargoService.Get(id);
            ViewBag.Title = "EDIT";
            if (cargo == null)
            {
                cargo = new Cargo();
                ViewBag.Title = "ADD";
            }

            return PartialView("_CreateEdit", cargo);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateEdit(Cargo model)
        {
            ViewBag.Title = model.Id == 0 ? "ADD" : "EDIT";
            if (!ModelState.IsValid)
            {
                return View("_CreateEdit", model);
            }
            try
            {
                model.Code = model.Code.Trim();
                _cargoService.Save(model);
                return Content("success");
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("Code", "Data sudah ada");
                return View("_CreateEdit", model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("_CreateEdit", model);
            }
        }

        public ActionResult Delete(int Id)
        {
            var cargo = _cargoService.Get(Id);
            return PartialView("_Delete", cargo);
        }

        // POST: Admin/Role/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteAction(int id)
        {
            try
            {
                _cargoService.Delete(id);
                return Content("success");
            }
            catch (DbUpdateException ex)
            {
                var sqlException = ex.GetBaseException() as SqlException;
                var cargo = _cargoService.Get(id);

                if (sqlException != null)
                {
                    var number = sqlException.Number;

                    if (number == 547)
                    {
                        ModelState.AddModelError("", "Data tidak dapat dihapus karena sudah digunakan.");
                        return View("_Delete", cargo);
                    }
                }
                ModelState.AddModelError("", ex.Message);
                return View("_Delete", cargo);
            }
            catch (Exception ex)
            {
                var cargo = _cargoService.Get(id);
                ModelState.AddModelError("", ex.Message);
                return View("_Delete", cargo);
            }
        }
    }
}

ProjectPertamina.Presentation/Views/Cargo/Index.cshtml
@model ProjectPertamina.Entities.Models.Cargo
<div class="container-content">
    <div class="title-admin">
        CARGO
    </div>
    <div class="isi-content">
        <div class="row sorting-table">
            <div class="col-md-10">
                <form class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(i => i.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-3">
                            @Html.TextBox("Code", "", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(i => i.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-3">
                            @Html.TextBox("Description", "", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-9">
                            <input type="button" class="btn btn-primary btn-sm" value="Search" id="btnSearch" />
                        </div>
                    </div>
                </form>
            </div>
        </div>

        @if (ViewBag.Create == true)
        {
            <div class="table-header">
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-url="@Url.Action("Create", "Cargo")" id="btnCreate">Add Cargo</button>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-url="@Url.Action("Upload", "Cargo")" id="btnUploadExcel">Upload Excel</button>
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" id="ButtonDownload">Download Template</button>
            </div>
        }
        <input type="hidden" id="hdActionedit" value="@ViewBag.Edit.ToString()" />
        <input type="hidden" id="hdActiondelete" value="@ViewBag.Delete.ToString()" />
        <table id="Table" class="table table-striped table-bordered" cellspacing="0" style="width:100%"></table>
    </div>
</div>

<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="CreateAssetModal" aria-hidden="true" data-backdrop="static">
    <div id="createContainer">
    </div>
</div>

<script type="text/javascript">
    //Other Script
    $("#ButtonDownload").on("click", function (e) {
        e.preventDefault();  //stop the browser from following
        window.location.href = 'ExcelTemplate/Cargo_Template.xlsx';
    });
</script>

<script type="text/javascript">
    //Table Script
    var assetListVM;
    //Login
    var edit = $('#hdActionedit').val();
    var hapus = $('#hdActiondelete').val();
    var visible = true;
    if (edit == "False" && hapus == "False")
        visible = false;
    //Login
    $(function () {
        assetListVM = {
            dt: null,

            init: function () {
                dt = $('#Table').DataTable({
                    "serverSide": true,
                    "processing": true,
                    "searching": false,
                    "ordering": false,
                    "ajax": {
                        "url": "@Url.Action("Get","Cargo")",
                        "data": function (data) {
                            //function search
                            data.Code = $("#Code").val();
                            data.Desc = $("#Description").val();
                        }
                    },
                    "columnDefs": [
                        {
                            "targets": [0],
                            "visible": visible
                        },
                    ],
                    "columns": [
                        {
                            "className": "dt-center",
                            "width": "100px",
                            "title": "<span class='glyphicon glyphicon-cog'></span>",
                            "data": "Id",
                            "sortable": false,
                            "render": function (data, type, full, meta) {
                                var action = "";
                                if (edit == "True") {
                                    action = '<a class="btn btn-primary btn-sm editAsset" href="@Url.Action("Create", "Cargo")?Id=' + data + '"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>';
                                }
                                if (hapus == "True") {
                                    action = action + ' <a href="@Url.Action("Delete", "Cargo")?Id=' + data + '" class="delete btn btn-danger btn-sm delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>';
                                }
                                return action;
                            }
                        },
                        { "title": "Kode", "data": "Code", "sortable": false },
                        { "title": "Deskripsi", "data": "Desc", "sortable": false },
                    ],
                    "lengthMenu": [[10, 25, 50, 100], [10, 25, 50, 100]],
                    "dom": '<"top">rt<"bottom"lip><"clear">'
                });
            },

            refresh: function () {
                dt.ajax.reload();
            }
        }
        $('#btnSearch').on("click", assetListVM.refresh);

        assetListVM.init();

        $("#btnCreate").on("click", function () {

            var url = $(this).data("url");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $("#btnUploadExcel").on("click", function () {

            var url = $(this).data("url");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $('#Table').on("click", ".editAsset", function (event) {

            event.preventDefault();

            var url = $(this).attr("href");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

        $('#Table').on("click", ".delete", function (event) {

            event.preventDefault();

            var url = $(this).attr("href");

            $.get(url, function (data) {
                $('#createContainer').html(data);

                $('#createModal').modal('show');
            });

        });

    });

</script>

ProjectPertamina.Presentation/Views/Cargo/_CreateEdit.cshtml
@model ProjectPertamina.Entities.Models.Cargo

@{
    Layout = null;
}

<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">@ViewBag.Title CARGO</h4>
        </div>
        @using (Ajax.BeginForm("CreateEdit", "Cargo", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "CreateSuccess" }, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group required">
                        @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-sm-8">
                            @if (ViewBag.Title == "ADD")
                            {
                                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", maxlength = "12" } })
                            }
                            else
                            {
                                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", maxlength = "12", @readonly = "" } })
                            }
                            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group required">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-sm-8">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", maxlength = "250" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary btn-sm" value="Save" />
                @*                <input type="button" class="btn btn-primary btn-sm" value="Save" id="ButtonSave" data-url="@Url.Action("CreateEdit","Cargo")" />*@
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
            </div>
        }
    </div>
</div>

ProjectPertamina.Presentation/Views/Cargo/_Delete.cshtml
@model ProjectPertamina.Entities.Models.Cargo

@{
    Layout = null;
    ViewBag.Title = "Delete";
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Delete</h4>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h4>Apakah Anda yakin menghapus (@Html.DisplayFor(model => model.Description))?</h4>

        </div>

        <div class="modal-body">
            @using (Ajax.BeginForm("Delete", "Cargo", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "DeleteSuccess" }, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="form-actions no-color">
                    @Html.HiddenFor(x => x.Id)
                    <input type="submit" value="Delete" class="btn btn-default btn-sm" />
                    <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Cancel</button>
                </div>
            }
        </div>
    </div>
</div>

ProjectPertamina.Presentation/Views/Cargo/_Upload.cshtml
@using ProjectPertamina.Common

@{
    Layout = null;
}

<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">UPLOAD CARGO</h4>
        </div>
        <form id="FormPopup">
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @*<div class="form-group">
                            @Html.Label("DownloadFile", "Template Excel", htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-3">
                                <input type="button" class="btn btn-primary btn-sm" value="Download" id="ButtonDownload"/>
                            </div>
                        </div>*@
                    <div class="form-group divgambar" data-provides="fileupload">
                        @Html.Label("NamaFile", "Excel", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            <input type="file" class="form-control" name="InputExcel" id="InputExcel" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
                            <p class="text-danger" id="ErrorMsg">@Html.Raw(ViewBag.Error)</p>
                            @Html.ValidationMessage("tes", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="button" class="btn btn-primary btn-sm" value="Save" id="ButtonSave" data-url="@Url.Action("Upload","Cargo")" />
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $("#ButtonSave").on("click", function () {
        var url = $(this).data("url");

        var data = new FormData();
        var files1 = $("#InputExcel").get(0).files;
        if (files1.length > 0) {
            data.append("FileUpload", files1[0]);
        }
        else {
            $("#ErrorMsg").html("Harap masukan file Excel");
            return;
        }

        $.ajax({
            url: url + '?' + $("#FormPopup").serialize(),
            type: "POST",
            data: data,
            contentType: false,
            processData: false,
            success: function (data) {
                CreateSuccess(data);
            },
            error: function (err) {
                alert(err.statusText);
            }
        });

    });

    //$("#ButtonDownload").on("click", function (e) {
    //    e.preventDefault();  //stop the browser from following
    //    window.location.href = 'ExcelTemplate/Cargo_Template.xlsx';
    //});

</script>