ProjectPertamina.Presentation/Areas/Admin/Controllers/BeritaController.cs
using DataTables.Mvc;
using ProjectPertamina.Common;
using ProjectPertamina.Entities.Models;
using ProjectPertamina.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;

namespace ProjectPertamina.Presentation.Areas.Admin.Controllers
{
    public class BeritaController : BaseController
    {
        private IBeritaService _beritaService;
        private IBeritaDetailService _beritaDetailService;
        private IKategoriBeritaService _kategoriBeritaService;

        public BeritaController(IBeritaService BeritaService, IBeritaDetailService BeritaDetailService, IKategoriBeritaService KategoriBeritaService)
        {
            _beritaService = BeritaService;
            _beritaDetailService = BeritaDetailService;
            _kategoriBeritaService = KategoriBeritaService;
        }


        public ActionResult Index()
        {
            var Kategori = _kategoriBeritaService.GetAll().ToList();
            Kategori.Insert(0, new KategoriBerita() { Kategori = "All", Id = 0 });
            ViewBag.Kategori = Kategori;
            return View(new Berita());
        }

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel,
        int Kategori, string JudulBerita,
        DateTime? Tanggal, DateTime? Sampai, string Penulis, string Sumber, string IsiBerita)
        {
            var obj = _beritaService.SearchBerita(requestModel.Start, requestModel.Length, Kategori, JudulBerita, Tanggal, Sampai, Penulis, Sumber, IsiBerita);
            //var obj = _beritaService.SearchBerita(requestModel.Start, requestModel.Length, Kategori, "", DateTime.Now, DateTime.Now, "", "", "");


            var data = obj.Item1.Select(berita => new
            {
                Id = berita.Id,
                Kategori = berita.KategoriBerita.Kategori,
                Judul = berita.Judul,
                Tanggal = berita.Tanggal,
                Penulis = berita.Penulis,
                Sumber = berita.Sumber,
                Isi = berita.IsiBerita.Count() > 25 ? berita.IsiBerita.Substring(0, 25) + "..." : berita.IsiBerita
            });

            #region Sorting
            //var sortedColumns = requestModel.Columns.GetSortedColumns();
            //var orderByString = String.Empty;

            //foreach (var column in sortedColumns)
            //{
            //    orderByString += orderByString != String.Empty ? "," : "";
            //    orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            //}
            //data = data.OrderBy(orderByString == string.Empty ? "Kategori asc" : orderByString);
            #endregion

            // Paging
            //data = data.Skip(requestModel.Start).Take(requestModel.Length);

            return Json(new DataTablesResponse(requestModel.Draw, data.ToList(), obj.Item3, obj.Item2), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            var role = _beritaService.Get(Id);

            return PartialView("_Delete", role);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteAction(int id)
        {
            string message = string.Empty;
            try
            {
                var berita = _beritaService.Get(id);
                foreach (var item in berita.BeritaDetails)
                {
                    DeleteFile(item.Gambar, ConstantKonfigurasiParameter.Berita);
                }
                _beritaService.Delete(id);
                return Content("success");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }


        public ActionResult IndexDetail(int id = 0)
        {
            var Kategori = _kategoriBeritaService.Find(i => i.Status);
            ViewBag.Kategori = Kategori;

            List<SelectListItem> Status = new List<SelectListItem>();
            Status.Add(new SelectListItem() { Text = "Yes", Value = "True" });
            Status.Add(new SelectListItem() { Text = "No", Value = "False" });
            ViewBag.Status = Status;

            if (id == 0)
            {
                ViewBag.Title = "Add Berita";
                return View(new Berita() { Tanggal = DateTime.Now, Status = true });
            }
            else
            {
                ViewBag.Title = "Edit Berita";
                return View(_beritaService.Get(id));
            }
        }

        public ActionResult GetDetail([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel, int BeritaId = 0)
        {
            //var obj = _beritaService.SearchBerita(requestModel.Start, requestModel.Length, Kategori, JudulBerita, Tanggal, Sampai, Penulis, Sumber, IsiBerita);
            var obj = _beritaService.Get(BeritaId);
            if (obj == null)
                obj = new Berita();
            var count = obj.BeritaDetails.Count();
            var data = obj.BeritaDetails.Select(beritaDetail => new
            {
                Id = beritaDetail.Id,
                Gambar = beritaDetail.Gambar,
                Date = beritaDetail.CreatedDate
            });

            // Paging
            data = data.Skip(requestModel.Start).Take(requestModel.Length);

            return Json(new DataTablesResponse(requestModel.Draw, data.ToList(), count, count), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreateEdit(HttpPostedFileBase[] files, Berita berita)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("IndexDetail", new { id = berita.Id });
            try
            {
                //beritaDetail.Gambar = ConvertToBytes(file);
                _beritaService.Save(berita);
                foreach (HttpPostedFileBase file in files)
                {
                    //Checking file is available to save.  
                    if (file != null)
                    {
                        _beritaDetailService.Save(new BeritaDetail() { Gambar = SaveFile(file, ConstantKonfigurasiParameter.Berita), BeritaId = berita.Id });
                    }
                }
                Success();
                return RedirectToAction("IndexDetail", new { id = berita.Id });
            }
            catch (Exception)
            {
                Danger();
                return RedirectToAction("IndexDetail", new { id = berita.Id });
            }

        }

        public ActionResult DeleteDetail(int Id)
        {
            var role = _beritaDetailService.Get(Id);

            if (Request.IsAjaxRequest())
                return PartialView("_DeleteDetail", role);
            return View(role);
        }

        [HttpPost, ActionName("DeleteDetail")]
        public ActionResult DeleteDetailAction(int id)
        {
            try
            {
                var beritaDetail = _beritaDetailService.Get(id);
                string Gambar = beritaDetail.Gambar;
                if (!string.IsNullOrEmpty(Gambar)) //check ada gambar lama?
                {
                    DeleteFile(Gambar, ConstantKonfigurasiParameter.Berita);
                }
                _beritaDetailService.Delete(id);
                return Content("success");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("_CreateEdit");
            }
        }
    }
}

ProjectPertamina.Presentation/Areas/User/Controllers/BeritaController.cs
using PagedList;
using ProjectPertamina.Entities.Models;
using ProjectPertamina.Entities.ViewModel;
using ProjectPertamina.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectPertamina.Presentation.Areas.User.Controllers
{
    public class BeritaController : Controller
    {
        private IBeritaService _beritaService;
        private IBeritaDetailService _beritaDetailService;
        private IKategoriBeritaService _kategoriBeritaService;

        public BeritaController(IBeritaService BeritaService, IBeritaDetailService BeritaDetailService, IKategoriBeritaService KategoriBeritaService)
        {
            _beritaService = BeritaService;
            _beritaDetailService = BeritaDetailService;
            _kategoriBeritaService = KategoriBeritaService;
        }
        // GET: User/Berita
        //public ActionResult Index(int id, int? page)
        //{
        //    IEnumerable<Berita> berita = _beritaService.GetAll();
        //    int pageSize = 12;
        //    int pageNumber = (page ?? 1);
        //    var BeritaID = _beritaService.GetAll().Select(m => m.Id);
        //    ViewData["BeritaDetail"] = _beritaDetailService.GetAll();

        //    var kat = _kategoriBeritaService.Get(id);
        //    ViewBag.KategoriBerita = kat.Kategori;

        //    return View(berita.ToPagedList(pageNumber, pageSize));

        //}
        public ActionResult Index(int id, int? page)
        {
            IEnumerable<Berita> model = _beritaService.Find(m => m.KategoriBeritaId == id);//GetAll().Where(m => m.Id == Id);
            var berita = model.Select(x => new BeritaViewModel
            {
                Id = x.Id,
                KategoriBeritaId = x.KategoriBeritaId,
                IsiBerita = x.IsiBerita.Substring(0, 500),
                Judul = x.Judul,
                Penulis = x.Penulis,
                Sumber = x.Sumber,
                Tanggal = x.Tanggal
            });
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            ViewData["BeritaDetail"] = _beritaDetailService.GetAll();
            var kat = _kategoriBeritaService.Get(id);
            ViewBag.KategoriBerita = kat.Kategori;
            return View(berita.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Detail(int Id)
        {
            IEnumerable<Berita> model = _beritaService.GetAll();
            var berita = model.Where(m => m.Id == Id);
            var jd = _beritaService.Get(Id);
            ViewBag.JudulBerita = jd.Judul;
            ViewBag.IdKat = jd.KategoriBeritaId;
            var idKat = jd.KategoriBeritaId;
            var kat = _kategoriBeritaService.Get(idKat);
            ViewBag.KategoriBerita = kat.Kategori;
            ViewData["BeritaDetail"] = _beritaDetailService.GetAll().Where(m => m.BeritaId == Id).ToList();
            return View(berita);
        }
    }
}

ProjectPertamina.Presentation/Areas/User/Views/Berita/Detail.cshtml
@using ProjectPertamina.Common;
@model IEnumerable<ProjectPertamina.Entities.Models.Berita>
<div class="container-content">
    <div class="title">
        <p style="text-align:left; margin-left:10px">@Html.ActionLink("Berita & Info", "Index", "Home", null, new { @class = "detail-content" }) &gt; <a class="detail-content" href='@Url.Action("Index", "Berita", new { @Id = ViewBag.IdKat})'>@ViewBag.KategoriBerita</a> &gt; @ViewBag.JudulBerita </p>
    </div>
    @foreach (var item in Model)
    {
        <div class="isi-content">
            <strong>@Html.ActionLink(item.Judul, "Detail", "Berita", new { @id = item.Id }, new { @class = "detail-content" })</strong>
            <h6>@item.Penulis | @item.CreatedDate.Value.ToString("dd MMM yyyy")</h6>

            @Html.Raw(HttpUtility.HtmlDecode(item.IsiBerita))
            <div class="row container-img">
                @{
                    foreach (var itemDetail in ViewData["BeritaDetail"] as List<ProjectPertamina.Entities.Models.BeritaDetail>)
                    {
                        <div class="col-md-2 img-berita">
                            <a href="#" class="pop">
                                <img src="@Url.Action("imagerRDP", "Base", new { KeyKonfigParam = ConstantKonfigurasiParameter.Berita, ImageName = itemDetail.Gambar })" />
                            </a>
                        </div>
                    }
                }
            </div>
        </div>
      }
</div>

ProjectPertamina.Presentation/Areas/User/Views/Berita/Index.cshtml
@using PagedList.Mvc;
@using ProjectPertamina.Common;
@model PagedList.IPagedList<ProjectPertamina.Entities.ViewModel.BeritaViewModel>
<div class="container-content">
    <div class="title">
        <p style="text-align:left; margin-left:10px">@Html.ActionLink("Berita & Info", "Index", "Home", null, new { @class = "detail-content" }) &gt; @ViewBag.KategoriBerita </p>

    </div>
    @foreach (var item in Model)
    {
        <div class="row isi-content">
            <p><strong>@Html.ActionLink(item.Judul, "Detail", "Berita", new { @id = item.Id }, new { @class = "detail-content" })</strong></p>
            <p><h6>@item.Penulis | @item.Tanggal.ToString("dd MMM yyyy")</h6></p>

            @Html.Raw(HttpUtility.HtmlDecode(item.IsiBerita))
            <div class="row container-img">
                @{
                    //int i = 0;
                    foreach (var itemDetail in (ViewData["BeritaDetail"] as List<ProjectPertamina.Entities.Models.BeritaDetail>).Where(m => m.BeritaId == item.Id))
                    {
                        <div class="col-md-2 img-berita">
                            <a href="#" class="pop">
                                <img src="@Url.Action("imagerRDP", "Base", new { KeyKonfigParam = ConstantKonfigurasiParameter.Berita, ImageName = itemDetail.Gambar })"/>
                            </a>
                        </div>
                        //i++;
                    }
                }
            </div>
        </div>
    }
    <div class="row paging">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
</div>

<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <img src="" class="imagepreview" style="width: 100%;">
            </div>
        </div>
    </div>
</div>